export const API_TOKEN_ID = '/auth/generate-access-token';
export const API_EMAIL_TOKEN = '/auth/email-authenticated';
export const API_TOKEN = '/auth/generate-token';
export const API_VALIDATE_TOKEN = '/auth/validate';
export const API_VACATIONS_ABSENCES = '/vacations';
export const API_HOLDERS = '/procedure-holder-fees';
export const API_HOLDER_LIST = '/holder';
export const API_NOTES = '/note';
export const API_NOTICE = '/notice';
export const API_HOLDER_NOTICE = '/holder-notice';
export const API_CONTACTS = '/contacts';
export const API_LIST_TYPE = '/catalog-generics/21?language_id=1';
export const API_MINDBREEZE = '/mindbreeze';
export const API_POSTAL_CODE = '/postal-code/fullByCode';

// Catalogs
export const API_AREA_SORTED_PHASES = '/area-sorted-phases';
export const API_AREA_SORTED_PHASE = '/area-sorted-phase';
export const API_SORTED_PHASES = '/sorted-phases';
export const API_AREA_INVOICE_CONCEPT = '/area-invoiceconcept';
export const API_PAYMENT_RIGHTS = '/payment-rights';
export const API_JOB_AREAS = '/job-areas';
export const API_JOB_AREAS_USER = '/job-areas-user';
export const API_EMPLOYEES = '/employees';
export const API_JOBAREAS_PROCEDUREPHASES = '/jobareas-procedurephases';
export const API_PROCEDURE_PHASES = '/procedure-phases';
export const API_PROCEDURE_SEARCH_JOB = '/type-search-jobs';
export const API_LEVEL = '/levels';
export const API_REMINDERS = '/reminders';
export const API_NOTIFICATIONS_IMPI = '/document-notifications';
export const API_PERMISSION_LEVELS = '/permission-levels';
export const API_CORRESPONDENCES_TITLES = '/correspondence-titles';
export const API_CORESPONSIBLE_USR = 'coresponsible/usr-id';
export const API_CORESPONSIBLE = 'coresponsible';
export const API_USERS = '/users';
export const API_USER_PROCEDURE_PHASES = '/user-procedurephases';
export const API_MACHOTE_RELATIONSHIP = '/machote-relationship-ppm-documents';
export const API_CURRENCIES = '/currency';
export const API_SIGNATURES = '/signatories';
export const API_FILES = '/files';
export const API_FILES_DOCUMENT = '/files/document';
export const API_COUNTRY_CURRENCY = '/country-currency';
export const GET_JOBAREAS_PROCEDUREPHASES = '/jobareas-procedurephases';
export const API_JOBAREAS_SIGNATURE = '/jobareas-signatories';
export const GET_REFERENCE_TYPES = '/reference-types/';
export const API_TMP_REPO_FOLDERS = '/tmp-repo-folders';
export const API_MANAGEMENTS = '/impi-address';
export const API_SUB_MANAGEMENTS = '/impi-subaddresses';
export const API_JOBAREA_MANAGEMENTS = '/job-area-impi-address';
export const API_JOBAREA_MANAGEMENT_SUBMANAGEMENTS = '/job-area-impi-address-subaddress';
export const API_IMPI_PAYMENTS = '/impi-payments';
export const API_IMPI_PAYMENTS_LISTS = '/impi-payment-lists';
export const API_IMPI_PAYMENTS_LISTS_LIST = '/impi-payment-lists/list';
export const API_COUNTRIES = '/countries';
export const API_LANGUAGES = '/languages';
export const API_MAILS = '/emails';
export const API_COUNTRIES_LANGUAGES = '/country-language/';
export const API_NOTICES = '/noticename';
export const API_NOTICES_USER = '/areauser-noticename';
export const API_NOTICES_INVOICE = '/invoiceconcept-noticename';
export const API_NOTICES_JOBAREA = '/jobarea-noticename';
export const API_COORDINATIONS = '/coordinations/';
export const API_SUBLABELS = '/subtags';
export const API_REFERENCE_TYPE_CLASSES = '/reference-type-class/';
export const API_PPM_CLASSES = '/ppm-class';
export const API_INVOICE_CONCEPT = '/invoiceconcept';
export const API_TYPE_CLASSES = '/class-type/';
export const API_INSTRUCTIONS_TYPES = '/instruction-types';
export const API_INSTRUCTIONSTYPES_PAYMENTSRIGHTS =
  '/instructiontypes-paymentrights';
export const API_PROCESSES = '/procedure-management-actions';
export const API_ACTION_NOTIFICATION_RECIPENT =
  '/action-notification-recipient';
export const API_CLIENT_RECIPIENT = '/client-recipient';
export const API_NOTIFICATIONS = '/action-notification/';
export const API_IMPI_DOCUMENTS = '/impi-documents/';
export const API_BANKS = '/banks';
export const API_AUTHORITIES = '/authorities';
export const API_COSTUMER_DOCUMENTS = '/docsclientphase';
export const API_CATALOG_GENERICS = '/catalog-generics';
export const GET_CURRENCIES = '/currency';
export const API_DEFAULT_NOTES = '/predetermined-notes';
export const GET_PRIORITIES = '/catalog-generics/3?language_id=1';
export const API_LEGAL_FIGURES = '/legal-figures';
export const API_PROCEDURE_TYPES = '/procedure-types';
export const API_LEGAL_PROCEDURE_FIGURES = '/legalfigures-proceduretypes';
export const API_JOBAREAS_REFERENCE_TYPES = '/jobareas-referencetypes';
export const API_PPM_DOCUMENTS = '/ppm-document';
export const API_PROCEDURE_NANAGEMENT_ACTIONS = '/procedure-management-actions';
export const GET_DOCUMENT_TYPE = '/type-document';
export const GET_CUSTOMER_LETTER_TYPE = '/customer-letter-type';
export const GET_LANGUAGES = '/languages';
export const GET_TEMPLATE_TYPES = '/catalog-generics/2?language_id=1';
export const GET_AGENTS = '/agents';
export const GET_HOLDERS = '/holder';
export const API_INVOICING_CONCEPTS = '/invoiceconcept';
export const GET_ARTICLE_TYPE = '/catalog-generics/7';
export const GET_CONCEPT_TYPE = '/catalog-generics/13?language_id=1';
export const API_PAYMENT_RIGHT_INVOICE_CONCEPT = '/paymentright-invoiceconcept';
export const API_AUTORITY_NOTIFICATION = '/autority-notifications';
export const API_AUTORITY_NOTIFICATION_PHASES = '/autority-notification-phases';
export const API_AUDIT_LOG = '/audit-log';

// Generals
export const API_INVOICING_ENTITIES = '/billing-entities';
export const API_INVOICING_ENTITIES_FOREIGN = '/billing-entities-foreign';
export const API_AGENT_INVOICING_ENTITIES = '/agents-billing-entities';
export const API_AGENT_INVOICING_ENTITIES_AGENT =
'/agents-billing-entities/agent';
export const API_HOLDER_INVOICING_ENTITIES = '/holder-billing-entity';
export const API_OFFICE_INVOICING_ENTITIES = '/office-billing-entities';
export const GET_PERSON_TYPE = '/catalog-generics/14?language_id=1';
export const GET_PAY_METHOD = '/catalog-generics/15?language_id=1';
export const GET_REGIME = '/catalog-generics/16?language_id=1';
export const GET_WAY_PAY = '/catalog-generics/17?language_id=1';
export const GET_CFDI = '/catalog-generics/18?language_id=1';
export const API_PAYMENT_TYPE = '/catalog-generics/24?language_id=1';
export const API_OFFICE_EMAIL_HEADERS = '/office-email-headers';
export const API_CLIENT_EMAIL_HEADERS = '/client-email-headers';
export const API_HOLDER_EMAIL_HEADERS = '/holder-email-headers';
export const API_OFFICE_EMAIL_HEADERS_VARIABLE =
'/office-email-header-variables';
export const API_CLIENT = '/agents';
export const API_CLIENT_SEARCH = '/agents/search';
export const API_CLIENT_UPDATE_ADM_STATUS = '/agents/update-adm-status';
export const API_INVENTORS = '/inventors';
export const API_PROCEDURES = '/procedures';
export const API_PROCEDURE_INVENTORS = '/procedure-inventors';
export const API_PROCEDURE_RENEWAL = '/procedure-renewals/procedure';
export const API_PROCEDURES_AGENT = '/procedure-agents';
export const API_PROCEDURES_HOLDER = '/procedure-holders';
export const API_PROCEDURES_HOLDER_PROCEDURE = '/procedure-holders/procedure';
export const API_PROCEDURE_REQUEST = '/procedure-request';
export const API_OFFICE = '/offices';
export const API_OFFICES_AGENT = '/offices/agent/';
export const API_EVIRTUAL = '/evirtual';
export const GET_COUNTRY_ABBREVIATIONS =
  '/catalog-generics/13948?language_id=1';
